name=input("Enter a name : ")
admission_number=input("Enter the admission number : ")
gender=input("Enter the gender : ")
classs=input("Enter the class :")
place=input("Enter the place : ")
father_name=input("Enter the father_name : ")
blood_group=input("Enter the blood group :")
phone_number=input("Enter the phone number : ")
print("-"*50)
print("name             :  "+name)
print("admission_number :  "+admission_number)
print("gender           :  "+gender)
print("classs           :  "+classs)
print("place            :  "+place)
print("father name      :  "+father_name)
print("blood group      :  "+blood_group)
print("phone_number     :  "+phone_number)
print("-"*50)